INSERT INTO country VALUES(DEFAULT,'Afganistan');	
INSERT INTO country VALUES(DEFAULT,'Albania');
INSERT INTO country VALUES(DEFAULT,'Algeria');
INSERT INTO country VALUES(DEFAULT,'American Samoa');
INSERT INTO country VALUES(DEFAULT,'Andorra');
INSERT INTO country VALUES(DEFAULT,'Angola');
INSERT INTO country VALUES(DEFAULT,'Anguilla');							
INSERT INTO country VALUES(DEFAULT,'Antigua &amp; Barbuda');
INSERT INTO country VALUES(DEFAULT,'Argentina');
INSERT INTO country VALUES(DEFAULT,'Armenia');
INSERT INTO country VALUES(DEFAULT,'Aruba');
INSERT INTO country VALUES(DEFAULT,'Australia');
INSERT INTO country VALUES(DEFAULT,'Austria');
INSERT INTO country VALUES(DEFAULT,'Azerbaijan');
INSERT INTO country VALUES(DEFAULT,'Bahamas');
INSERT INTO country VALUES(DEFAULT,'Bahrain');
INSERT INTO country VALUES(DEFAULT,'Bangladesh');
INSERT INTO country VALUES(DEFAULT,'Barbados');
INSERT INTO country VALUES(DEFAULT,'Belarus');
INSERT INTO country VALUES(DEFAULT,'Belgium');
INSERT INTO country VALUES(DEFAULT,'Belize');
INSERT INTO country VALUES(DEFAULT,'Benin');
INSERT INTO country VALUES(DEFAULT,'Bermuda');
INSERT INTO country VALUES(DEFAULT,'Bhutan');
INSERT INTO country VALUES(DEFAULT,'Bolivia');
INSERT INTO country VALUES(DEFAULT,'Bonaire');
INSERT INTO country VALUES(DEFAULT,'Bosnia &amp; Herzegovina');
INSERT INTO country VALUES(DEFAULT,'Botswana');
INSERT INTO country VALUES(DEFAULT,'Brazil');
INSERT INTO country VALUES(DEFAULT,'British Indian Ocean Ter');
INSERT INTO country VALUES(DEFAULT,'Brunei');
INSERT INTO country VALUES(DEFAULT,'Bulgaria');
INSERT INTO country VALUES(DEFAULT,'Burkina Faso');
INSERT INTO country VALUES(DEFAULT,'Burundi');
INSERT INTO country VALUES(DEFAULT,'Cambodia');
INSERT INTO country VALUES(DEFAULT,'Cameroon');
INSERT INTO country VALUES(DEFAULT,'Canada');
INSERT INTO country VALUES(DEFAULT,'Canary Islands');
INSERT INTO country VALUES(DEFAULT,'Cape Verde');
INSERT INTO country VALUES(DEFAULT,'Cayman Islands');
INSERT INTO country VALUES(DEFAULT,'Central African Republic');			


INSERT INTO country VALUES(DEFAULT,'Chad');
INSERT INTO country VALUES(DEFAULT,'Channel Islands');				

INSERT INTO country VALUES(DEFAULT,'Chile');
INSERT INTO country VALUES(DEFAULT,'China');					
INSERT INTO country VALUES(DEFAULT,'Christmas Island');
INSERT INTO country VALUES(DEFAULT,'Cocos Island');							
INSERT INTO country VALUES(DEFAULT,'Colombia');
INSERT INTO country VALUES(DEFAULT,'Comoros');					
INSERT INTO country VALUES(DEFAULT,'Congo');
INSERT INTO country VALUES(DEFAULT,'Cook Islands');					
INSERT INTO country VALUES(DEFAULT,'Costa Rica');
INSERT INTO country VALUES(DEFAULT,'Cote DIvoire');						
INSERT INTO country VALUES(DEFAULT,'Croatia');
INSERT INTO country VALUES(DEFAULT,'Cuba');
INSERT INTO country VALUES(DEFAULT,'Curaco');
INSERT INTO country VALUES(DEFAULT,'Cyprus');
INSERT INTO country VALUES(DEFAULT,'Czech Republic');
INSERT INTO country VALUES(DEFAULT,'Denmark');
INSERT INTO country VALUES(DEFAULT,'Djibouti');
INSERT INTO country VALUES(DEFAULT,'Dominica');
INSERT INTO country VALUES(DEFAULT,'Dominican Republic');
INSERT INTO country VALUES(DEFAULT,'East Timor');
INSERT INTO country VALUES(DEFAULT,'Ecuador');
INSERT INTO country VALUES(DEFAULT,'Egypt');
INSERT INTO country VALUES(DEFAULT,'El Salvador');
INSERT INTO country VALUES(DEFAULT,'Equatorial Guinea');							
INSERT INTO country VALUES(DEFAULT,'Eritrea');
INSERT INTO country VALUES(DEFAULT,'Estonia');
INSERT INTO country VALUES(DEFAULT,'Ethiopia');
INSERT INTO country VALUES(DEFAULT,'Falkland Islands');
INSERT INTO country VALUES(DEFAULT,'Faroe Islands');
INSERT INTO country VALUES(DEFAULT,'Fiji');
INSERT INTO country VALUES(DEFAULT,'Finland');
INSERT INTO country VALUES(DEFAULT,'France');
INSERT INTO country VALUES(DEFAULT,'French Guiana');
INSERT INTO country VALUES(DEFAULT,'French Polynesia');
INSERT INTO country VALUES(DEFAULT,'French Southern Ter');

INSERT INTO country VALUES(DEFAULT,'Gabon');
INSERT INTO country VALUES(DEFAULT,'Gambia');
INSERT INTO country VALUES(DEFAULT,'Georgia');
INSERT INTO country VALUES(DEFAULT,'Germany');
INSERT INTO country VALUES(DEFAULT,'Ghana');
INSERT INTO country VALUES(DEFAULT,'Gibraltar');
INSERT INTO country VALUES(DEFAULT,'Great Britain');
INSERT INTO country VALUES(DEFAULT,'Greece');
INSERT INTO country VALUES(DEFAULT,'Greenland');
INSERT INTO country VALUES(DEFAULT,'Grenada');
INSERT INTO country VALUES(DEFAULT,'Guadeloupe');
INSERT INTO country VALUES(DEFAULT,'Guam');
INSERT INTO country VALUES(DEFAULT,'Guatemala');
INSERT INTO country VALUES(DEFAULT,'Guinea');
INSERT INTO country VALUES(DEFAULT,'Guyana');
INSERT INTO country VALUES(DEFAULT,'Haiti');
INSERT INTO country VALUES(DEFAULT,'Hawaii');
INSERT INTO country VALUES(DEFAULT,'Honduras');
INSERT INTO country VALUES(DEFAULT,'Hong Kong');
INSERT INTO country VALUES(DEFAULT,'Hungary');
INSERT INTO country VALUES(DEFAULT,'Iceland');
INSERT INTO country VALUES(DEFAULT,'India');
INSERT INTO country VALUES(DEFAULT,'Indonesia');
INSERT INTO country VALUES(DEFAULT,'Iran');
INSERT INTO country VALUES(DEFAULT,'Iraq');
INSERT INTO country VALUES(DEFAULT,'Ireland');
INSERT INTO country VALUES(DEFAULT,'Isle of Man');
INSERT INTO country VALUES(DEFAULT,'Israel');
INSERT INTO country VALUES(DEFAULT,'Italy');
INSERT INTO country VALUES(DEFAULT,'Jamaica');
INSERT INTO country VALUES(DEFAULT,'Japan');
INSERT INTO country VALUES(DEFAULT,'Jordan');
INSERT INTO country VALUES(DEFAULT,'Kazakhstan');
INSERT INTO country VALUES(DEFAULT,'Kenya');
INSERT INTO country VALUES(DEFAULT,'Kiribati');
INSERT INTO country VALUES(DEFAULT,'Korea North');
INSERT INTO country VALUES(DEFAULT,'Korea Sout');
INSERT INTO country VALUES(DEFAULT,'Kuwait');
INSERT INTO country VALUES(DEFAULT,'Kyrgyzstan');
INSERT INTO country VALUES(DEFAULT,'Laos');
INSERT INTO country VALUES(DEFAULT,'Latvia');
INSERT INTO country VALUES(DEFAULT,'Lebanon');
INSERT INTO country VALUES(DEFAULT,'Lesotho');
INSERT INTO country VALUES(DEFAULT,'Liberia');
INSERT INTO country VALUES(DEFAULT,'Libya');
INSERT INTO country VALUES(DEFAULT,'Liechtenstein');
INSERT INTO country VALUES(DEFAULT,'Lithuania');
INSERT INTO country VALUES(DEFAULT,'Luxembourg');
INSERT INTO country VALUES(DEFAULT,'Macau');
INSERT INTO country VALUES(DEFAULT,'Macedonia');
INSERT INTO country VALUES(DEFAULT,'Madagascar');
INSERT INTO country VALUES(DEFAULT,'Malaysia');
INSERT INTO country VALUES(DEFAULT,'Malawi');
INSERT INTO country VALUES(DEFAULT,'Maldives');
INSERT INTO country VALUES(DEFAULT,'Mali');
INSERT INTO country VALUES(DEFAULT,'Malta');
INSERT INTO country VALUES(DEFAULT,'Marshall Islands');

INSERT INTO country VALUES(DEFAULT,'Martinique');
INSERT INTO country VALUES(DEFAULT,'Mauritania');
INSERT INTO country VALUES(DEFAULT,'Mauritius');
INSERT INTO country VALUES(DEFAULT,'Mayotte');
INSERT INTO country VALUES(DEFAULT,'Mexico');
INSERT INTO country VALUES(DEFAULT,'Midway Islands');
INSERT INTO country VALUES(DEFAULT,'Moldova');
INSERT INTO country VALUES(DEFAULT,'Monaco');
INSERT INTO country VALUES(DEFAULT,'Mongolia');
INSERT INTO country VALUES(DEFAULT,'Montserrat');
INSERT INTO country VALUES(DEFAULT,'Morocco');
INSERT INTO country VALUES(DEFAULT,'Mozambique');
INSERT INTO country VALUES(DEFAULT,'Myanmar');
INSERT INTO country VALUES(DEFAULT,'Nambia');
INSERT INTO country VALUES(DEFAULT,'Nauru');
INSERT INTO country VALUES(DEFAULT,'Nepal');
INSERT INTO country VALUES(DEFAULT,'Netherland Antilles');
INSERT INTO country VALUES(DEFAULT,'Netherlands');
INSERT INTO country VALUES(DEFAULT,'Nevis');
INSERT INTO country VALUES(DEFAULT,'New Caledonia');
INSERT INTO country VALUES(DEFAULT,'New Zealand');
INSERT INTO country VALUES(DEFAULT,'Nicaragua');
INSERT INTO country VALUES(DEFAULT,'Niger');
INSERT INTO country VALUES(DEFAULT,'Nigeria');
INSERT INTO country VALUES(DEFAULT,'Niue');
INSERT INTO country VALUES(DEFAULT,'Norfolk Island');
INSERT INTO country VALUES(DEFAULT,'Norway');
INSERT INTO country VALUES(DEFAULT,'Oman');
INSERT INTO country VALUES(DEFAULT,'Pakistan');
INSERT INTO country VALUES(DEFAULT,'Palau Island');
INSERT INTO country VALUES(DEFAULT,'Palestine');
INSERT INTO country VALUES(DEFAULT,'Panama');
INSERT INTO country VALUES(DEFAULT,'Papua New Guinea');
INSERT INTO country VALUES(DEFAULT,'Paraguay');
INSERT INTO country VALUES(DEFAULT,'Peru');
INSERT INTO country VALUES(DEFAULT,'Phillipines');
INSERT INTO country VALUES(DEFAULT,'Pitcairn Island');
INSERT INTO country VALUES(DEFAULT,'Poland');
INSERT INTO country VALUES(DEFAULT,'Portugal');
INSERT INTO country VALUES(DEFAULT,'Puerto Rico');
INSERT INTO country VALUES(DEFAULT,'Qatar');
INSERT INTO country VALUES(DEFAULT,'Republic of Montenegro');
INSERT INTO country VALUES(DEFAULT,'Republic of Serbia');
INSERT INTO country VALUES(DEFAULT,'Reunion');
INSERT INTO country VALUES(DEFAULT,'Romania');
INSERT INTO country VALUES(DEFAULT,'Russia');
INSERT INTO country VALUES(DEFAULT,'Rwanda');
INSERT INTO country VALUES(DEFAULT,'St Barthelemy');
INSERT INTO country VALUES(DEFAULT,'St Eustatius');
INSERT INTO country VALUES(DEFAULT,'St Helena');
INSERT INTO country VALUES(DEFAULT,'St Kitts-Nevis');
INSERT INTO country VALUES(DEFAULT,'St Lucia');
INSERT INTO country VALUES(DEFAULT,'St Maarten');
INSERT INTO country VALUES(DEFAULT,'St Pierre &amp; Miquelon');
INSERT INTO country VALUES(DEFAULT,'St Vincent &amp; Grenadines');
INSERT INTO country VALUES(DEFAULT,'Saipan');
INSERT INTO country VALUES(DEFAULT,'Samoa');
INSERT INTO country VALUES(DEFAULT,'Samoa American');
INSERT INTO country VALUES(DEFAULT,'San Marino');
INSERT INTO country VALUES(DEFAULT,'Sao Tome &amp; Principe');
INSERT INTO country VALUES(DEFAULT,'Saudi Arabia');
INSERT INTO country VALUES(DEFAULT,'Senegal');
INSERT INTO country VALUES(DEFAULT,'Serbia');
INSERT INTO country VALUES(DEFAULT,'Seychelles');
INSERT INTO country VALUES(DEFAULT,'Sierra Leone');
INSERT INTO country VALUES(DEFAULT,'Singapore');
INSERT INTO country VALUES(DEFAULT,'Slovakia');
INSERT INTO country VALUES(DEFAULT,'Slovenia');
INSERT INTO country VALUES(DEFAULT,'Solomon Islands');
INSERT INTO country VALUES(DEFAULT,'Somalia');
INSERT INTO country VALUES(DEFAULT,'South Africa');
INSERT INTO country VALUES(DEFAULT,'Spain');
INSERT INTO country VALUES(DEFAULT,'Sri Lanka');
INSERT INTO country VALUES(DEFAULT,'Sudan');
INSERT INTO country VALUES(DEFAULT,'Suriname');
INSERT INTO country VALUES(DEFAULT,'Swaziland');
INSERT INTO country VALUES(DEFAULT,'Sweden');
INSERT INTO country VALUES(DEFAULT,'Switzerland');
INSERT INTO country VALUES(DEFAULT,'Syria');
INSERT INTO country VALUES(DEFAULT,'Tahiti');
INSERT INTO country VALUES(DEFAULT,'Taiwan');
INSERT INTO country VALUES(DEFAULT,'Tajikistan');
INSERT INTO country VALUES(DEFAULT,'Tanzania');
INSERT INTO country VALUES(DEFAULT,'Thailand');
INSERT INTO country VALUES(DEFAULT,'Togo');
INSERT INTO country VALUES(DEFAULT,'Tokelau');
INSERT INTO country VALUES(DEFAULT,'Tonga');
INSERT INTO country VALUES(DEFAULT,'Trinidad &amp; Tobago');
INSERT INTO country VALUES(DEFAULT,'Tunisia');
INSERT INTO country VALUES(DEFAULT,'Turkey');
INSERT INTO country VALUES(DEFAULT,'Turkmenistan');
INSERT INTO country VALUES(DEFAULT,'Turks &amp; Caicos Is');							
INSERT INTO country VALUES(DEFAULT,'Tuvalu');
INSERT INTO country VALUES(DEFAULT,'Uganda');
INSERT INTO country VALUES(DEFAULT,'Ukraine');
INSERT INTO country VALUES(DEFAULT,'United Arab Erimates');
INSERT INTO country VALUES(DEFAULT,'United Kingdom');
INSERT INTO country VALUES(DEFAULT,'United States of America');
INSERT INTO country VALUES(DEFAULT,'Uraguay');
INSERT INTO country VALUES(DEFAULT,'Uzbekistan');
INSERT INTO country VALUES(DEFAULT,'Vanuatu');
INSERT INTO country VALUES(DEFAULT,'Vatican City State');
INSERT INTO country VALUES(DEFAULT,'Venezuela');
INSERT INTO country VALUES(DEFAULT,'Vietnam');
INSERT INTO country VALUES(DEFAULT,'Virgin Islands (Brit)');
INSERT INTO country VALUES(DEFAULT,'Virgin Islands (USA)');
INSERT INTO country VALUES(DEFAULT,'Wake Island');
INSERT INTO country VALUES(DEFAULT,'Wallis &amp; Futana Is');
INSERT INTO country VALUES(DEFAULT,'Yemen');
INSERT INTO country VALUES(DEFAULT,'Zaire');
INSERT INTO country VALUES(DEFAULT,'Zambia');
INSERT INTO country VALUES(DEFAULT,'Zimbabwe');